
#----------------------------
#GitHub Actions Part 1- Base
#
#Copyleft(C) by Ren Sal 2023
#----------------------------

name: myGitHubActionsBase1
env:
  APPLICATION_NAME        : 'myFlask'
  DEPLOY_PACKAGE_NAME     : 'flask_deploy_ver_${{ github.sha }}'
 

on:
 push:
   branches: 
         - master

jobs:


 my_test:
  runs-on: ubuntu-latest
  steps:
    - name: Print Hello Message in Test
      run: echo 'Hello world from testing'

    - name: Execute few commands
      run: |
        echo 'Hello Message1'
        echo 'Hello Message1'
        echo 'Application name: ${{env.APPLICATION_NAME}}'
        
   

 my_deploy:
  runs-on: ubuntu-latest
  needs: [my_test]
  steps:
    - name: Print Hello Message in Deploy
      run: echo 'Hello world from deploy'
      
    - name: Printing Deployment package
      run: echo 'Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}'
